version: "3.8"
services:
  postgres:
    image: "postgres:16.0-alpine"
    container_name: shop_container
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
    volumes:
      - shop_data:/var/lib/postgresql/data

volumes:
  shop_data: