version: "1"
services:
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_ENABLE_CORS_FOR_API: "true"
      MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES: "true"
      MOCKSERVER_CORS_ALLOW_ORIGIN: "*"
      MOCKSERVER_CORS_ALLOW_METHODS: "*"
    volumes:
      - ./initializerJson.json:/config/initializerJson.json:Z
